# Generated by Django 5.2.4 on 2025-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Время, когда было отправлено последнее напоминание о привычке.",
                null=True,
                verbose_name="Время последней отправки напоминания",
            ),
        ),
    ]
